config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  resources :channels, only: [:index]
  post 'add_to_favourite' => 'channels#add_to_favourite'
  root to: 'channels#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/channel.rb
class Channel < ApplicationRecord
	has_many :shows, dependent: :destroy


	def self.search search
		result = []
		if search
			shows = Show.where(['name like ?', '%' + search + '%'])
			channels = self.where(['name like ?', '%' + search + '%'])
			result << shows
			result << channels
			result.flatten
		else
			Channel.all
		end
	end
end

app/models/show.rb
class Show < ApplicationRecord
	belongs_to :channel
	has_and_belongs_to_many :users
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
 	has_and_belongs_to_many :shows
 	validates :email, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
	skip_before_action :verify_authenticity_token, if: -> { request.format.json? || request.format.xml? || request.format.js? }
	before_action :authenticate_user!
end

app/controllers/channels_controller.rb
class ChannelsController < ApplicationController

	def index
		@channels = Channel.search(params[:search])
	end

	def add_to_favourite
		show_ids = current_user.show_ids
		show_ids << params[:show_id]
		show_ids = show_ids.flatten
		current_user.update(show_ids: show_ids)
	end
end

app/controllers/shows_controller.rb
class ShowsController < ApplicationController
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/channels_helper.rb
module ChannelsHelper
end

app/helpers/shows_helper.rb
module ShowsHelper
end

app/views/channels/index.html.erb
<% if params[:commit] == "Search" %>
	<h2> Search Results </h2>
<% else %>
	<h2> Channels </h2>
<% end %>


<% if @channels.present? %>
	<% @channels.each do |channel| %>
		<ul>
			<li> <%= channel.name %> </li>
		</ul>
		<% unless params[:commit] == "Search" %>
			<ul>
				<% channel.shows.each do |show| %>
					<li> <%= show.name %>
						<button onclick='addFavourite(<%= "#{show.id}" %>)'> Add to Favourite </button>
					 </li>
				<% end %>
			</ul>
		<% end %>
	<% end %>
<% else %>
	No Channels or Shows found
<% end %>

<script>
	function addFavourite(show_id){
		$.ajax({
			type: 'POST',
			url: "/add_to_favourite",
			data: {
    		show_id: show_id
    	},
    	dataType: 'JSON',
			success: function(result){
    		alert("Added to Favourite");
  		}});
	}
</script>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TvShowApp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
  </head>

  <body>
    <h2> Welcome to your TV </h2>
    <%= form_tag(channels_path, method: :get) do %>
      <%= text_field_tag :search, params[:search] %>
      <%= submit_tag ("Search") %>
    <% end %>
    <%= yield %>
  </body>
</html>